import type { Metadata } from "next";

import localFont from "next/font/local";

import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers/providers";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiasedm min-h-dvh",
        )}
      >
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
