on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: keyb's-shop    # 设置为你的应用程序名称
  AZURE_WEBAPP_PACKAGE_PATH: '.'    # 设置为你的Web应用项目路径，默认为仓库根目录
  NODE_VERSION: '22.9.0'            # 设置为要使用的Node.js版本

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 设置 Node.js 版本
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 安装 pnpm
      run: npm install -g pnpm

    - name: 验证 pnpm 是否可用
      run: pnpm --version

    - name: 安装依赖并生成锁定文件
      run: pnpm install

    - name: 构建项目
      run: |
        pnpm run build --if-present
        pnpm run test --if-present

    - name: 上传构建工件
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 下载构建工件
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 部署到 Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
