on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: keyb's-shop
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.9.0'

permissions:
  contents: read

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 设置 Node.js 版本
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 安装 pnpm
      run: npm install -g pnpm

    - name: 验证 pnpm 是否可用
      run: pnpm --version

    - name: 安装依赖并生成锁定文件
      run: pnpm install

    - name: 设置环境变量
      env:
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
        AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
        AUTH_RESEND_KEY: ${{ secrets.AUTH_RESEND_KEY }}
        AUTH_URL: ${{ secrets.AUTH_URL }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      run: |
        echo "环境变量已设置。"

    - name: 构建项目
      run: pnpm run build

    - name: 上传构建工件
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 下载构建工件
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 部署到 Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
